apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"